---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bm-amq-producer
  name: bm-amq-producer
  namespace: amq-producer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  - name: 9779-tcp
    port: 9779
    protocol: TCP
    targetPort: 9779
  selector:
    app: bm-amq-producer
    deploymentconfig: bm-amq-producer
  sessionAffinity: None
  type: ClusterIP
