---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-state
  labels:
    app: bm-amq-consumer
  namespace: amq-consumer
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
